version: "3.3"

# docker-compose.yml configuration for a Traefik reverse-proxy with dashboard.
#
#  Environment Variables:
#    PORTAINER_INITIAL_PASSWORD_HASH
#                            The initial bcrypt-hashed password of the Portainer 'admin' account to use for
#                            bootstrapping Portainer security. It is meant to be temporary. The first time
#                            you log into Portainer, you will log in with username 'admin' and the password
#                            associated with this hash. At that time, you should immediately change the
#                            password to a durable hard-to-guess password.
#                            After you have changed the password, this value is no longer used, unless
#                            you wipe Portainer state by recreating the 'portainer_data' volume.
#
#                            The value of this string is similar to that produced by `htpasswd`, but does not include
#                            the '<username>:' prefix normally produced by the `htpasswd` command. It can be generated using
#                            `htpasswd -nB admin | sed 's/[^:]*://'` or set with `hub config set-portainer-initial-password`.
#                            This value is sensitive because it can be used for an offline dictionary attack,
#                            and should not be stored in a git repository. It should not be set to a re-used password.
#
#                            Note that this value may contain dollar-signs, so if it is directly inserted
#                            in a docker-compose.yml file, each dollar-sign must be doubled. That is
#                            automatically taken care of when the value is expanded from an environment
#                            variable, as it is here.
#    PORTAINER_CERT_RESOLVER
#                            "prod" or "staging".  The certificate resolver to use for portainer.{PARENT_DNS_DOMAIN}
#                                 "prod" uses real lets-encrypt certificates, "staging" uses staging lets-encrypt
#    PORTAINER_DNS_NAME      The fully qualified public DNS domain that the Portainer web UI will run on.
#                            There must be a DNS entry for this name that resolves to this network's public IP address.}
#    PORTAINER_AGENT_SECRET  A secret string that is shared between portainer and portainer_agent.  This is used to
#                                 authenticate the agent to portainer and vice-versa.
#    PORTAINER_INJECTED_ENVIRONMENT_VARS
#                            A YAML-encoded property list, indented 6 spaces on all but the first line,
#                            listing additional environment variable assignments to pass into the container
#    PORTAINER_LOG_LEVEL     The log level for Portainer.  One of "DEBUG", "INFO", "WARN", "ERROR", "FATAL", "PANIC"
#    PORTAINER_AGENT_LOG_LEVEL
#                            The log level for Portainer.  One of "DEBUG", "INFO", "WARN", "ERROR", "FATAL", "PANIC"
#
# Entrypoints:
#    This stack uses the following Traefik reverse-proxy entrypoints:
#
#    Entrypoint      Port   Description
#    ----------      ----   ---------------------------------
#    web             7080   Intended to serve public HTTP requests; public port 80 on the network's gateway
#                             router should be port-forwarded to this port. Also used to serve challenge
#                             requests from lets-encrypt to verify ownership of domain names.
#    websecure       7443   Intended to serve public HTTPS requests; public port 443 on the network's gateway
#                             router should be port-forwarded to this port.
#    lanweb            80   Serves HTTP requests for LAN-local clients
#    lanwebsecure     443   Serves HTTPS requests for LAN-local clients. to be used without certificate errors,
#                             A public DNS name must resolve externally to this network's public IP address,
#                             but must resolve within the LAN to this host's LAN IP address. This can be done
#                             by putting the LAN IP address in each client's /etc/hosts, or by hosting
#                             a LAN-local DNS server that overrides the public entries.
#    portainerui     9000   Serves the Portainer UI on LAN-local http://<any-hostname>:9000.
#
# Externally, this stack serves:
#    https://${PORTAINER_DNS_NAME}          Portainer UI (private LAN only). Requires a /hosts entry on each client, or a LAN-local DNS server.
#    http://${PORTAINER_DNS_NAME}           Redirects to https:// (private LAN only)
#    http://<any-host>:9000                 Portainer UI (private LAN only)
#
# Portainer is only exposed on the LAN, but for HTTPS routes it requires a hostname that resolves publicly to this network's publid IP address. This
# is the only way to get a valid lets-encrypt certificate for ${PORTAINER_DNS_NAME}. So by default, browser clients
# will get "404 page not found" when they navigate to https://${PORTAINER_DNS_NAME}. There are 2 ways to make it work:
#
#  1. Add a /etc/hosts entry on each client that points ${PORTAINER_DNS_NAME} to this host's LAN IP address.
#  2. Run a LAN-local DNS server that overrides the public DNS entries for ${PORTAINER_DNS_NAME} and points them to this host's LAN IP address,
#     and use a LAN-local DHCP server to configure each client to use the LAN-local DNS server.
#
# If this is not feasible, you can still use portainer from inside the LAN without HTTPS by navigating to http://${HUB_LAN_IP}:9000.
#
# Prerequisites:
#   Prerequisites common to all stacks (only done once when traefik is initially set up):
#     * The traefik docker-compose stack has been installed and runs on this host, and can create certificates
#       for DNS names that route to this network's public IP address.
#     * A DNS CNAME entry has been created for ${PORTAINER_DNS_NAME} that resolves to this network's public IP address.
#       You must create a DNS entry for ${PORTAINER_DNS_NAME} that resolves to your gateway router's public IP address
#       *before* starting this stack. If you do not, lets-encrypt will be unable to validate the certificate request,
#       and will eventually throttle you for a week at a time.
#     * A persistent docker volume "portainer_data" has been created before launching. This volume will contain all the
#       persistent state associated with portainer, including its username/password has database and ACL
#       information.  This volume should never be deleted unless you want to wipe portainer.
#
services:
  portainer_agent:
    # A portainer agent that provides access to docker on the local host.
    # also allows docker volumes to be browsed and edited. Only used by
    # portainer
    image: portainer/agent:2.18.4
    environment:
      # REQUIRED: Should be equal to the service name prefixed by "tasks." when
      # deployed inside an overlay network
      AGENT_CLUSTER_ADDR: tasks.portainer-agent
      # AGENT_PORT: 9001
      LOG_LEVEL: ${PORTAINER_AGENT_LOG_LEVEL}
      AGENT_SECRET: '${PORTAINER_AGENT_SECRET}'   # allows portainer to authenticate to the agent
    ports:
      # The agent needs to be reachable on port 9001, but only within the stack.
      # So no need to expose.  The agent is added to portainer with the address
      # "portainer_agent: 9001"     
      # - 9001:9001
      []
    volumes:
      - portainer_data:/data                              # Persistent data for the agent
      - /var/run/docker.sock:/var/run/docker.sock         # Allows the agent to control docker on the local host
      - /var/lib/docker/volumes:/var/lib/docker/volumes   # Allows portainer UI browsing of docker volumes (and upload/download)
      - /:/host                                           # Allows portainer UI browsing of entire host filesystem (and upload/download)
    networks:
      - portainer_agent     # allows portainer to see the agent. Nothing else needs access
    restart: always

  portainer:
    image: portainer/portainer-ce:latest
    extends:
      file: injected-env-vars.yml
      service: injected_env_vars
    environment:
      # AGENT_PORT: 9001
      LOG_LEVEL: ${PORTAINER_LOG_LEVEL}
      AGENT_SECRET: '${PORTAINER_AGENT_SECRET}'    # allows portainer to authenticate to the agent
    command:
      # Initial password hash for the 'admin' account.  This is a temporary password that is only used
      # on first launch, or when the portainer_data volume is wiped.  It is meant to be changed immediately
      # after first login.  It is not used after that.
      - "--admin-password=${PORTAINER_INITIAL_PASSWORD_HASH:-}"
    ports:
      - 8000:8000    # SSH tunnel entrypoint; used by edge portainer agents to connect to portainer server
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - traefik           # allows traefik to forward requests to portainer
      - portainer_agent   # allows portainer to connect to the local portainer agent on port 9001
    labels:
      # expose Portainer web UI (port 9000 in the container) behind the traefik reverse-proxy (LAN only) at https://${PORTAINER_DNS_NAME}.
      # The client will need to add a /etc/hosts entry to point ${PORTAINER_DNS_NAME} at this host's LAN IP.
      - "traefik.enable=true"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"     # Port 9000 is reverse-proxied

      # A router for https://${PORTAINER_DNS_NAME}
      - "traefik.http.routers.portainer.entrypoints=lanwebsecure"
      - "traefik.http.routers.portainer.tls.certresolver=${PORTAINER_CERT_RESOLVER}"
      - "traefik.http.routers.portainer.rule=Host(`${PORTAINER_DNS_NAME}`)"

      # A router for http://${PORTAINER_DNS_NAME} that redirects to https
      - "traefik.http.routers.portainer-http.entrypoints=lanweb"
      - "traefik.http.routers.portainer-http.rule=Host(`${PORTAINER_DNS_NAME}`)"
      - "traefik.http.routers.portainer-http.middlewares=portainer-https"
      - "traefik.http.middlewares.portainer-https.redirectscheme.scheme=https"

      # A router for http://<any-hostname>:9000
      - "traefik.http.routers.portainer-http-path.entrypoints=portainerui"
      - "traefik.http.routers.portainer-http-path.rule=HostRegexp(`{host:.+}`)"   # matches any hostname

    restart: always

volumes:
  portainer_data:
    # Persistent data for portainer. Includes sensitive data suct as portainer database, authorized user credential metadata, etc.
    external: true

networks:
  traefik:
    # Traefik's docker network.  Allows traefik to forward HTTP requests to backend services. Any
    # service behind the traefik reverse-proxy must be in at least this network.
    external: true
  portainer_agent:
    # a backend network that allows portainer to connect to the local portainer_agent service. Nothing
    # else needs to connect to it.
