version: "3"
services:
  public-iface-container:
    image: qmcgaw/gluetun:latest
    container_name: publicip-container
    cap_add:
      - NET_ADMIN
    ports:
      - 8888:8888/tcp # HTTP proxy
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - purevpn-public-ip-vpn-data:/vpn-conf:ro
      - gluetun-data:/gluetun
    environment:
      - "VPN_SERVICE_PROVIDER=custom"
      - "VPN_TYPE=openvpn"
      #- "VPN_INTERFACE=publicip"
      - "OPENVPN_CUSTOM_CONFIG=/vpn-conf/purevpn.ovpn"
      - "FIREWALL_VPN_INPUT_PORTS=80,443"
      - "OPENVPN_USER=${OPENVPN_USER}"
      - "OPENVPN_PASSWORD=${OPENVPN_PASSWORD}"
volumes:
  purevpn-public-ip-vpn-data:
    external: true
  gluetun-data: {}
